### ISSUE TITLE
Issue with migrating from v0.14.3 to v0.16.0

### ISSUE THREAD

**Issue by kskarthik** [Pylons/pyramid_openapi3#212]
So, I tried migration & got this error. Did i miss anything? Please help me resolve

```bash
Starting monitor for PID 15.
gkcore_1       | Traceback (most recent call last):
gkcore_1       |   File "<string>", line 1, in <module>
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/hupper/ipc.py", line 319, in spawn_main
gkcore_1       |     func(**kwargs)
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/hupper/worker.py", line 283, in worker_main
gkcore_1       |     func(*spec_args, **spec_kwargs)
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid/scripts/pserve.py", line 30, in main
gkcore_1       |     return command.run()
gkcore_1       |            ^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid/scripts/pserve.py", line 271, in run
gkcore_1       |     app = loader.get_wsgi_app(app_name, config_vars)
gkcore_1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/plaster_pastedeploy/__init__.py", line 111, in get_wsgi_app
gkcore_1       |     return loadapp(
gkcore_1       |            ^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 248, in loadapp
gkcore_1       |     return loadobj(APP, uri, name=name, **kw)
gkcore_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 273, in loadobj
gkcore_1       |     return context.create()
gkcore_1       |            ^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 741, in create
gkcore_1       |     return self.object_type.invoke(self)
gkcore_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/paste/deploy/loadwsgi.py", line 138, in invoke
gkcore_1       |     return fix_call(context.object, context.global_conf, **context.local_conf)
gkcore_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/paste/deploy/util.py", line 61, in fix_call
gkcore_1       |     val = callable(*args, **kw)
gkcore_1       |           ^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/gkcore/gkcore/__init__.py", line 220, in main
gkcore_1       |     config.include("pyramid_openapi3")
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid/config/__init__.py", line 632, in include
gkcore_1       |     c = self.maybe_dotted(callable)
gkcore_1       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
gkcore_1       |     return self.name_resolver.maybe_resolve(dotted)
gkcore_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid/path.py", line 327, in maybe_resolve
gkcore_1       |     return self._resolve(dotted, package)
gkcore_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid/path.py", line 334, in _resolve
gkcore_1       |     return self._zope_dottedname_style(dotted, package)
gkcore_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid/path.py", line 383, in _zope_dottedname_style
gkcore_1       |     found = __import__(used)
gkcore_1       |             ^^^^^^^^^^^^^^^^
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid_openapi3/__init__.py", line 3, in <module>
gkcore_1       |     from .exceptions import extract_errors
gkcore_1       |   File "/usr/local/lib/python3.11/site-packages/pyramid_openapi3/exceptions.py", line 5, in <module>
gkcore_1       |     from openapi_core.unmarshalling.schemas.exceptions import InvalidSchemaFormatValue
gkcore_1       | ImportError: cannot import name 'InvalidSchemaFormatValue' from 'openapi_core.unmarshalling.schemas.exceptions' (/usr
/local/lib/python3.11/site-packages/openapi_core/unmarshalling/schemas/exceptions.py)
```

**Comment by zupo** [comment]
Try using openapi_core < 0.17 and report back please.

**Comment by kskarthik** [comment]
Yes, Defining this way in requirements.txt works!

```
pyramid-openapi3 == 0.16.0
openapi-core < 0.17.0
```
