### ISSUE TITLE
openapi_core>0.13.3 (current master) is incompatible with `webob.EnvironHeaders`

### ISSUE THREAD

**Issue by huntcsg** [Pylons/pyramid_openapi3#78]
In a [recent commit](https://github.com/p1c2u/openapi-core/commit/ac5c6762d83aea911fcc6c3bc775f432532a287d), [PR](https://github.com/p1c2u/openapi-core/pull/236) in `openapi_core` a werkzeug headers class was introduced into the `openapi_core.validation.request.datatypes.RequestParameters ` initialization.

This causes a failure in header processing. 

A minimal test case is here: https://github.com/huntcsg/pyramid_openapi3_headers_testcase
Here is a stacktrace I captured from that:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.7/site-packages/pyramid_openapi3/tween.py", line 27, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid_openapi3/__init__.py", line 80, in wrapper_view
    openapi_request = PyramidOpenAPIRequestFactory.create(request)
  File "/usr/local/lib/python3.7/site-packages/pyramid_openapi3/wrappers.py", line 33, in create
    cookie=request.cookies,
  File "<attrs generated init openapi_core.validation.request.datatypes.RequestParameters>", line 7, in __init__
    self.header = __attr_converter_header(header)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py", line 958, in __init__
    self.extend(defaults)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py", line 1101, in extend
    for key, value in iter_multi_items(args[0]):
ValueError: too many values to unpack (expected 2)
```

**Comment by huntcsg** [comment]
The above PR fails a number of tests and I'm not sure if this is the right way to make this library compatible with the werkzeug change on the master branch of openapi_core. 

I'm happy to accept some input an prepare a more appropriate fix/tests.

**Comment by zupo** [comment]
Hey @huntcsg, thanks for a great bug report, they don't come in any better way than with a failing test! 

I have almost zero availability for the next two weeks so won't be able to look into this before June ~10. That said, I am very much happy to review any and all PRs!

**Comment by zupo** [comment]
Can't reproduce: https://github.com/Pylons/pyramid_openapi3/pull/79#issuecomment-647101433

**Comment by abuzakaria** [comment]
This error occurs for `openapi-core==0.13.4`. After I downgraded to `0.13.3`, everything works.
